# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_dgcmat_wrappers", use_symbols = TRUE, package_name = "dgcmat")

#' @docType package
#' @usage NULL
#' @useDynLib dgcmat, .registration = TRUE
NULL

#' Compute degree vector (row sums) of a dgCMatrix via Rust and faer.
#'
#' Passes the entire dgCMatrix S4 object to Rust. The Rust side extracts the
#' i, p, x slots via extendr, wraps them as zero-copy slices, constructs a
#' faer SparseColMat, computes row sums, and returns the result via
#' WritableSlice (writing directly into R-allocated memory).
#'
#' @param mat A dgCMatrix sparse matrix (from the Matrix package).
#' @return A numeric vector of row sums (degree vector).
#' @export
dgc_degree <- function(mat) {
  if (!inherits(mat, "dgCMatrix")) {
    stop("'mat' must be a dgCMatrix object (from the Matrix package)")
  }
  .Call("wrap__dgc_degree_rust", mat)
}
