# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_row_sum_wrappers", use_symbols = TRUE, package_name = "row_sum")

#' @docType package
#' @usage NULL
#' @useDynLib rowSum, .registration = TRUE
NULL

#' Compute row sums of a dense matrix using faer.
#' @param matrix A numeric matrix.
#' @return A numeric vector of row sums.
#' @export
row_sums_faer <- function(matrix) {
  if (!is.matrix(matrix)) stop("input must be a matrix")
  storage.mode(matrix) <- "double"
  .Call("wrap__row_sums_faer", matrix)
}
